import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/components/shared/provider/lenis-provider";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

const microgrammaBold = localFont({
  src: "../fonts/microgramma-bold.otf",
  variable: "--font-microgramma-sans",
});

const microgrammaMedium = localFont({
  src: "../fonts/microgramma-medium.otf",
  variable: "--font-microgramma-medium",
});


const orbitronExtrabold = localFont({
  src: "../fonts/orbitron-black.otf",
  variable: "--font-orbitron-extrabold",
});

const orbitronBold = localFont({
  src: "../fonts/orbitron-bold.otf",
  variable: "--font-orbitron-bold",
});

const orbitronLight = localFont({
  src: "../fonts/orbitron-light.otf",
  variable: "--font-orbitron-light",
});

const orbitronMedium = localFont({
  src: "../fonts/orbitron-medium.otf",
  variable: "--font-orbitron-medium",
});

export const metadata: Metadata = {
  title: "Home - Everglory Lines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <link rel="icon" href="/everglory-favicon.svg" sizes="any" />
      </head>
      <body
        className={`
        ${montserratSans.variable} 
        ${microgrammaBold.variable} 
        ${microgrammaMedium.variable}
        ${orbitronExtrabold.variable} 
        ${orbitronBold.variable} 
        ${orbitronLight.variable} 
        ${orbitronMedium.variable} 
        font-sans antialiased
        `}
      >
         <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
